### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by aude-darracq** [nlesc-ave/ave-rest-service#45]
Can you help me to have AVE2 running ?
DB is ready but I don't know how to run avedata 

avedata run
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)

**Comment by sverhoeven** [comment]
When you visit http://localhost:8080 with a web browser what do you see?

Do you see the following?:
```
{
  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}
```

That means you are just running the Python web service. To run the whole application you also need the [client side application](https://github.com/nlesc-ave/ave-app) and NGINX to host 2bit/bigbed files and NGINX configured to bundle everything behind a single host:port as described at https://github.com/nlesc-ave/ave-rest-service#deploy-on-bare-metalvirtual-machine .

The [ave2/allelic-variation-explorer](https://hub.docker.com/r/ave2/allelic-variation-explorer/) Docker image already has the client side application and NGINX configured correctly.

Are you using the Docker image or the non-Docker deployment method?

**Comment by sverhoeven** [comment]
In follow up emails & Skype meeting resolved the installation issues
