### ISSUE TITLE
gff.as

### ISSUE THREAD

**Issue by EdwinvZon** [nlesc-ave/ave-rest-service#46]
Dear reader,
thanks for the docker image and the new documentation it is looking very well.
However I still run into a problem, running the folliwing;
_root@9d44780e8968:/data# bedToBigBed -tab -type=bed6+4 -as=gff3.as genes.sorted.bed chrom.sizes genes.sorted.bb_
This gives me the following error:
_mustOpen: Can't open gff3.as to read: No such file or directory_
Do you have an idea what might be the problem?

Kind regards,

Edwin van Zon

**Comment by sverhoeven** [comment]
The gff3.as file can be downloaded from https://github.com/nlesc-ave/ave-rest-service/blob/master/gff3.as or is available inside Docker container at `/app/gff3.as`
